---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: deploy
  datasource:
    hikari:
      max-lifetime: 60000
      keepalive-time: 30000
      connection-timeout: 5000