name: Java CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
      - run: make build
      - run: make lint
      - run: make test
